setTimeout(()=>{
    document.getElementById("root").textContent=10
    setTimeout(()=>{
        document.getElementById("root").textContent=9
        setTimeout(()=>{
            document.getElementById("root").textContent=8
            setTimeout(()=>{
                document.getElementById("root").textContent=7
                setTimeout(()=>{
                    document.getElementById("root").textContent=6
                    setTimeout(()=>{
                        document.getElementById("root").textContent=5
                        setTimeout(()=>{
                            document.getElementById("root").textContent=4
                            setTimeout(()=>{
                                document.getElementById("root").textContent=3
                                setTimeout(()=>{
                                    document.getElementById("root").textContent=2
                                    setTimeout(()=>{
                                        document.getElementById("root").textContent=1
                                        setTimeout(()=>{
                                            document.getElementById("root").textContent="Happy Independence Day"
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)
